import type { Metadata } from "next";
import { Outfit, Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SessionAuthProvider } from "@/components/session-auth";
import {Toaster } from "sonner";

// Fonte para Títulos (Moderna, geométrica e amigável)
const outfit = Outfit({
  variable: "--font-heading",
  subsets: ["latin"],
});

// Fonte para Textos (Limpa, excelente legibilidade, padrão UI moderno)
const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

// Fonte para Códigos/Componentes (Visual tech e moderno)
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakarta.variable} ${outfit.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <SessionAuthProvider>
          <Toaster
          duration={2500}
          />
          {children}
          </SessionAuthProvider>
      </body>
    </html>
  );
}
